#ifndef NTC_H
#define NTC_H

#include <Arduino.h>
#include <avr/pgmspace.h>
#include "Pins.h"
#include "Config.h"

/*
  NTC.h — 3-channel thermistor read with running average.

  Three NTC inputs come into the Nano ADC after op-amp conditioning
  (TLV9004 quad op-amp on the Rev A board). Read all three each
  100 ms tick.

  Channel roles in THIS control scheme:
    NTC_1 (A1) — cold-side temperature.
                 This is the ONLY sensor the control loop uses for
                 its decision.

    NTC_2 (A2) — hot-side temperature.
                 Read and reported on the Serial Plotter but NOT
                 used for control in this rev.

    NTC_3 (A3) — ambient temperature.
                 Read and reported but NOT used for control.

  All three appear on the plotter line so the maker always has
  visibility, even though only NTC_1 drives the TEC.

  Temperature conversion
  ----------------------
  Two conversion models, selected by ENABLE_NTC_LUT in Config.h:

  ENABLE_NTC_LUT = 1 (default): nonlinear lookup table.
    T_lut(C) = interpolate(raw_ADC, NTC_LUT_RAW[], NTC_LUT_T10[])
    T(C)     = T_lut * trim_scale + trim_offset

    The table encodes the sensor's published R-T curve plus a
    bench-fitted correction against a reference thermometer, baked
    into (raw ADC count, temperature) pairs at ~5 C spacing with
    linear interpolation between entries. It is generated by the
    fitting script in the calibration application note (see the
    provenance block above the table below) and is SPECIFIC to one
    sensor model and one analog front end. Changing either means
    regenerating the table, not editing entries by hand.

    trim_scale / trim_offset (defaults 1.0 / 0.0) are a field
    touch-up on top of the table, set by the cal / cal1 / cal2
    serial commands and persisted via `save`. They exist so a
    small per-unit shift can be corrected without reflashing; the
    curve SHAPE always comes from the table.

    A raw reading outside the table returns NAN, which matches the
    existing unwired-channel semantics: the OVERTEMP check compares
    false on NAN, and a NAN control temperature parks the TEC.

  ENABLE_NTC_LUT = 0: legacy linear model.
    T(C) = raw_ADC * trim_scale + trim_offset
    with Config.h legacy defaults (NTC_SCALE_LEGACY = 0.1023,
    NTC_OFFSET_LEGACY = -27.6). Kept as a compile-time fallback so
    a build for a board with no fitted table behaves exactly like
    pre-LUT firmware. Note the legacy linear model was measured
    25 C wrong at 92 C true on the bench (2026-08-28 fit) — it is
    a placeholder, not a calibration.

  Running average
  ---------------
  Each channel maintains a circular buffer of NTC_AVG_LEN raw ADC
  samples (default 10). The conversion is applied to the averaged
  raw value for stability. At the 100 ms tick rate, the average
  spans the last 1 second of readings.
*/

#if ENABLE_NTC_LUT
// ---------------------------------------------------------------
// Calibration lookup table — PROGMEM, ~104 B.
//
// PROVENANCE (regenerate with fit_ntc_lut.py, do not hand-edit):
//   Sensor:    Amphenol Thermometrics TK95F103W (10k, curve F)
//   Curve:     AAS-913-318C Rev C p.12 material F
//   Fit:       deg-2 correction vs Calex Excelog 6 Type K,
//              2026-08-28 bench run, 169 quasi-steady points,
//              -4.3 to 95.2 C validated span (correction clamped
//              outside it, table extended on the datasheet curve)
//   Front end: R1=10k R2=4.75k R3=4.64k R4=68.1R, AREF=3.3 V,
//              10-bit ADC (Rev B board, stock network)
//   Residual:  2.7 C max, 1.1 C RMS vs the Type K reference
// ---------------------------------------------------------------
#define NTC_LUT_N 26
static const uint16_t NTC_LUT_RAW[NTC_LUT_N] PROGMEM = {
   111,  146,  186,  231,  282,  337,  394,  453,  511,  568,  622,  672,  718,
   759,  795,  828,  856,  880,  902,  920,  935,  949,  960,  970,  979,  986 };
static const int16_t  NTC_LUT_T10[NTC_LUT_N] PROGMEM = {  /* 0.1 C units */
  -185, -135,  -85,  -27,   31,   88,  145,  201,  257,  312,  366,  420,  473,
   525,  577,  628,  678,  728,  777,  825,  873,  920,  967, 1017, 1067, 1117 };

// Averaged-raw -> temperature via the table. Returns NAN when the
// reading falls outside the table (unwired channel, shorted input,
// or genuinely out of calibrated range).
static float _ntc_lut_convert(float raw) {
  const uint16_t lo_raw = pgm_read_word(&NTC_LUT_RAW[0]);
  const uint16_t hi_raw = pgm_read_word(&NTC_LUT_RAW[NTC_LUT_N - 1]);
  if (raw < lo_raw || raw > hi_raw) return NAN;

  // Binary search for the bracketing pair.
  uint8_t lo = 0, hi = NTC_LUT_N - 1;
  while (hi - lo > 1) {
    uint8_t mid = (uint8_t)((lo + hi) >> 1);
    if ((float)pgm_read_word(&NTC_LUT_RAW[mid]) <= raw) lo = mid; else hi = mid;
  }
  float r0 = (float)pgm_read_word(&NTC_LUT_RAW[lo]);
  float r1 = (float)pgm_read_word(&NTC_LUT_RAW[hi]);
  float t0 = (float)(int16_t)pgm_read_word(&NTC_LUT_T10[lo]) * 0.1f;
  float t1 = (float)(int16_t)pgm_read_word(&NTC_LUT_T10[hi]) * 0.1f;
  return t0 + (t1 - t0) * (raw - r0) / (r1 - r0);
}
#endif // ENABLE_NTC_LUT

// Runtime calibration trim — initialized from Config.h, adjustable
// via serial "cal" commands, persisted via `save`.
//   LUT build:    T = T_lut * _ntc_scale + _ntc_offset  (1.0 / 0.0)
//   legacy build: T = raw   * _ntc_scale + _ntc_offset  (0.1023 / -27.6)
static float _ntc_scale  = NTC_SCALE;
static float _ntc_offset = NTC_OFFSET;

// Per-channel circular buffer for running average.
static uint16_t _ntc_buf[3][NTC_AVG_LEN];
static uint8_t  _ntc_idx = 0;
static bool     _ntc_filled = false;  // true after first NTC_AVG_LEN samples

// Cached averaged raw ADC and converted temperatures.
static float _ntc_raw_avg[3] = { 0, 0, 0 };
static float _ntc_temp[3] = { NAN, NAN, NAN };
#if ENABLE_NTC_LUT
// Untrimmed table output, cached for the cal commands (the trim is
// solved in temperature domain, so it needs the pre-trim value).
static float _ntc_lut_temp[3] = { NAN, NAN, NAN };
#endif

inline void ntc_init() {
#if USE_EXTERNAL_AREF
  analogReference(EXTERNAL);
#endif
  // Zero the buffers.
  memset(_ntc_buf, 0, sizeof(_ntc_buf));
}

// Read all three NTC channels, feed the running average, and cache
// the converted temperatures. Call once per 100 ms tick. Returns the
// cold-side temperature (NTC_1) directly.
inline float ntc_readAll() {
  static const uint8_t pins[3] = { HW_NTC_1, HW_NTC_2, HW_NTC_3 };

  for (uint8_t ch = 0; ch < 3; ++ch) {
    _ntc_buf[ch][_ntc_idx] = analogRead(pins[ch]);
  }
  _ntc_idx = (_ntc_idx + 1) % NTC_AVG_LEN;
  if (_ntc_idx == 0) _ntc_filled = true;

  // Compute average from the filled portion of the buffer.
  uint8_t count = _ntc_filled ? NTC_AVG_LEN : _ntc_idx;
  if (count == 0) count = 1;  // guard against /0 on first call

  for (uint8_t ch = 0; ch < 3; ++ch) {
    uint32_t sum = 0;
    for (uint8_t i = 0; i < count; ++i) sum += _ntc_buf[ch][i];
    _ntc_raw_avg[ch] = (float)sum / count;
#if ENABLE_NTC_LUT
    _ntc_lut_temp[ch] = _ntc_lut_convert(_ntc_raw_avg[ch]);
    _ntc_temp[ch] = _ntc_lut_temp[ch] * _ntc_scale + _ntc_offset;
#else
    _ntc_temp[ch] = _ntc_raw_avg[ch] * _ntc_scale + _ntc_offset;
#endif
  }

  return _ntc_temp[0];  // cold-side
}

// Get the cached temperature for a given channel (1, 2, or 3).
inline float ntc_getC(uint8_t chan) {
  if (chan < 1 || chan > 3) return NAN;
  return _ntc_temp[chan - 1];
}

// Get the averaged raw ADC value for a channel (for calibration).
inline float ntc_getRawAvg(uint8_t chan) {
  if (chan < 1 || chan > 3) return 0;
  return _ntc_raw_avg[chan - 1];
}

#if ENABLE_NTC_LUT
// Get the cached UNTRIMMED table temperature for a channel — the
// value before trim_scale/trim_offset are applied. Used by the cal
// commands, which solve the trim in temperature domain.
inline float ntc_getLutC(uint8_t chan) {
  if (chan < 1 || chan > 3) return NAN;
  return _ntc_lut_temp[chan - 1];
}
#endif

// Get/set the runtime calibration constants.
inline float ntc_getScale()  { return _ntc_scale; }
inline float ntc_getOffset() { return _ntc_offset; }
inline void  ntc_setScale(float s)  { _ntc_scale = s; }
inline void  ntc_setOffset(float o) { _ntc_offset = o; }

#endif // NTC_H
